server:
    servlet:
        context-path: /dddsample

logging:
    level:
        jdbc: debug
        'se.citerus.dddsample': debug

uploadDirectory: /tmp/upload
parseFailureDirectory: /tmp/failed

brokerUrl: "vm://localhost?broker.persistent=false&broker.useJmx=false"

spring:
#    dataSource:
#        url: jdbc:hsqldb:mem:dddsample
#        username: sa
#        password: ""

    dataSource:
        url: jdbc:mysql://rocky:3306/dddsample
        username: app
        password: Password123=

#    jpa:
#        hibernate:
#            ddl-auto: update
#        database-platform: org.hibernate.dialect.MySQLDialect

jdbc:
    datasource-proxy:
        enabled: true
        query:
            logger-name: jdbc
            enable-logging: true
        multiline: false
        include-parameter-values: true
